<?php 
   $title = 'Delete an employee record'; 
   $this->headTitle($title);  
?> 
<h1><?php echo $this->escapeHtml($title); ?></h1>  

<p>Are you sure you want to delete '<?php echo $this->escapeHtml($employee->employee_name); ?>'</p>  
<?php 
   $url = $this->url('employee', array('action' => 'delete', 'id' => $this->employee_id,)); 
?>  

<form action ="<?php echo $url; ?>" method = "post">
   <div> 
      <input type = "hidden" name = "employee_id" value = "<?php echo (int) $employee->employee_id; ?>" /> 
      <input type = "submit" name = "del" value = "Yes" /> 
      <input type = "submit" name = "del" value = "No" /> 
   </div> 
</form> 