<?php 
$title = 'Employee application'; 
$this->headTitle($title); 
?>  
<br>
<div class="row">
<a class = "btn btn-success" href="<?php echo $this->url('employee',array('action'=>'add'));?>">Add Employee</a>
</div><br><br>

<div class="row">
<table id = "emptable" class="table table-striped table-bordered">
<thead> 
   <tr> 
      <th>Employee Id</th> 
      <th>Employee Name</th> 
	  <th>Address</th> 
	  <th>Email Address</th> 
	  <th>Phone</th> 
	  <th>Date of Birth</th> 
	  <th>Employee Image</th> 
      <th>Action</th>
   </tr> 
   </thead>
   <tbody>
   <?php foreach ($data as $empdata) : ?> 
   <tr>  
		<td><?php echo $this->escapeHtml($empdata->employee_id);?></td> 
		<td><?php echo $this->escapeHtml($empdata->employee_name);?></td>
		<td><?php echo $this->escapeHtml($empdata->address);?></td>
		<td><?php echo $this->escapeHtml($empdata->email_address);?></td>
		<td><?php echo $this->escapeHtml($empdata->phone);?></td>
		<td><?php echo $this->escapeHtml($empdata->date_of_birth);?></td>
		<td><a href="public/uploads/<?php echo $this->escapeHtml($empdata->employee_image);?>" target="_blank"><?php echo $this->escapeHtml($empdata->employee_image);?></a></td>	  
      <td> 
         <a class="btn btn-primary" href="<?php echo $this->url('employee', 
            array('action'=>'edit', 'id' =>$empdata->employee_id));?>">Edit</a> 
         <a class="btn btn-danger" href="<?php echo $this->url('employee', 
            array('action'=>'delete', 'id' => $empdata->employee_id));?>">Delete</a> 
      </td> 
   </tr> 
   <?php endforeach; ?> 
   </tbody>
</table>
</div>
<script>
$(document).ready(function() {
    $('#emptable').dataTable();
} );
</script>